# Generated by Django 4.2.17 on 2025-09-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
    ]
