# Generated by Django 4.2.17 on 2025-03-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='royalty_percentage',
            field=models.DecimalField(decimal_places=2, default=80.0, max_digits=5),
        ),
    ]
