app = "your-app-name"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  DJANGO_SETTINGS_MODULE = "your_project.settings"
  SECRET_KEY = "your-secret-key"
  DEBUG = "False"
  ALLOWED_HOSTS = "your-app-name.fly.dev"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0