# Generated by Django 4.2.17 on 2025-03-25 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('book_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='books.booktype')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='book_files/')),
                ('author', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.booktype')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.category')),
            ],
        ),
    ]
