# Generated by Django 4.2.17 on 2025-07-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
