# Generated by Django 4.2.17 on 2025-08-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_slug_alter_booktype_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
