# Generated by Django 4.2.17 on 2025-08-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_booktype_name_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktype',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
