# Generated by Django 4.2.17 on 2025-08-27 11:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0010_alter_booktype_name_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireWriterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Project/thesis writer', 'Project/thesis writer'), ('Data analysis', 'Data analysis'), ('Questionnaire', 'Questionnaire'), ('Assignment', 'Assignment'), ('Serminal', 'Serminal'), ('General', 'General (if the service not included)')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('topic', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('upload_format', models.FileField(blank=True, null=True, upload_to='writer_requests/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='submitted', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hire Writer Request',
                'verbose_name_plural': 'Hire Writer Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
