# Generated by Django 4.2.17 on 2025-09-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_hirewriterrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='book_files/'),
        ),
        migrations.AlterField(
            model_name='hirewriterrequest',
            name='service',
            field=models.CharField(choices=[('Project/thesis writer', 'Project/thesis writer'), ('Data analysis', 'Data analysis'), ('Questionnaire', 'Questionnaire'), ('Assignment', 'Assignment'), ('Serminal', 'Serminal'), ('Hire Developer', 'Hire Developer'), ('General', 'General (if the service not included)')], max_length=50),
        ),
    ]
