"""
Django settings for projectsandmaterials project.
Generated by 'django-admin startproject' using Django 4.2.17.
"""
import json
from pathlib import Path
from decouple import config
from google.oauth2 import service_account
from google.cloud import storage
import dj_database_url
from datetime import timedelta
from django.urls import reverse_lazy
import os

import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
YOUTUBE_API_KEY = config('YOUTUBE_API_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost 127.0.0.1 projectandmaterials.com www.projectandmaterials.com").split()
CORS_ALLOW_CREDENTIALS = True

SITE_URL = config("SITE_URL", default="http://127.0.0.1:8000")

# Application definition
INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'background_task',
    'books',
    'admin_app',
    'payments',
    'subscriptions',
    'rest_framework',
    'rest_framework_simplejwt',
    'users',
    'storages',
    
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'projectsandmaterials.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}



CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

AUTH_USER_MODEL = 'users.CustomUser'

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True

LOGIN_URL = '/users/user_login/'
ACCOUNT_SIGNUP_URL = 'users:register'
LOGIN_REDIRECT_URL = 'users:user-dashboard'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

WSGI_APPLICATION = 'projectsandmaterials.wsgi.application'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]


CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = 'Projects&Materials <edisonemeremnu@gmail.com>'

# Security Settings
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Database Configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASE_URL = config("DATABASE_URL", default="")
# if DATABASE_URL:
#     DATABASES["default"] = dj_database_url.parse(DATABASE_URL)

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'projec24_projectandmaterials_db',
#         'USER': 'projec24_projectandmaterials_db',
#         'PASSWORD': 'materialsProject@2025',  # the new password
#         'HOST': 'localhost',
#         'PORT': '3306',
#         'OPTIONS': {
#            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#         },
#     }
# }


GCS_CREDENTIALS_PATH = config("GOOGLE_APPLICATION_CREDENTIALS")

if not GCS_CREDENTIALS_PATH:
    raise Exception("GOOGLE_APPLICATION_CREDENTIALS not set")

# Django Storages + GCS
DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
#STATICFILES_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'

GS_BUCKET_NAME = config('GS_BUCKET_NAME')
GS_PROJECT_ID = config('GS_PROJECT_ID')
GS_CREDENTIALS = service_account.Credentials.from_service_account_file(GCS_CREDENTIALS_PATH)


PAYSTACK_SECRET_KEY = config('PAYSTACK_SECRET_KEY')
PAYSTACK_PUBLIC_KEY = config('PAYSTACK_PUBLIC_KEY')

FLUTTERWAVE_PUBLIC_KEY = config('FLUTTERWAVE_PUBLIC_KEY')
FLUTTERWAVE_SECRET_KEY = config('FLUTTERWAVE_SECRET_KEY')


# Social Account Providers
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': config('GOOGLE_CLIENT_ID'),
            'secret': config('GOOGLE_CLIENT_SECRET'),
            'key': ''
        }
    }
}

# Password Validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static Files Configuration
# URLs
#STATIC_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/static/"
#MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/media/"





# Static Files Configuration
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# # Media Files Configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default Primary Key Field Type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


JAZZMIN_SETTINGS = {
    "site_title": "Admin",
    "site_brand": "Admin Page",
    "site_logo": "books/images/brand.jpg",
    "welcome_sign": "Welcome to the Projectsandmaterials",
    "copyright": "Emrisolution Ltd",
    "theme": "materia",
    "dark_mode_theme": "solar",
   

    # "search_model": ["auth.User", "auth.Group"],
    
    "topmenu_links": [

        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},

        # model admin to link to (Permissions checked against model)
        {"model": "auth.User"},

        # App with dropdown menu to all its models pages (Permissions checked against models)
        {"app": "books"},
    ],
    
    "custom_links": {
        "auth": [  # or use any registered app label
            {
                "name": "Batch Upload",
                "url": reverse_lazy("admin_app:batch-upload"),
                "icon": "fas fa-life-ring",
                "new_window": True
            }
        ]
    },
    
"icons": {
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "account.EmailAddress": "fas fa-envelope",
        "books.Book": "fas fa-book",
        "books.BookType": "fas fa-tags",
        "books.Category": "fas fa-folder",
        "payments.Payment": "fas fa-money-bill-wave",
        "payments.Download": "fas fa-download",
        "payments.Order": "fas fa-shopping-cart",
        "payments.WithdrawalRequest": "fas fa-hand-holding-usd",
        "sites.Site": "fas fa-globe",
        "socialaccount.SocialAccount": "fas fa-share-alt",
        "socialaccount.SocialToken": "fas fa-key",
        "socialaccount.SocialApp": "fas fa-plug",
        "subscriptions.SubscriptionPlan": "fas fa-credit-card",
        "subscriptions.UserSubscription": "fas fa-user-check",
        "users.CustomUser": "fas fa-user-shield",
        "users.Profile": "fas fa-id-card",
    },

"show_ui_builder": False,

}
