# Generated by Django 4.2.17 on 2025-07-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='download_limit',
            field=models.IntegerField(default=0, help_text='0 means unlimited downloads'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='duration',
            field=models.IntegerField(help_text='Duration in days'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_28ce5e_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['status'], name='subscriptio_status_6805e6_idx'),
        ),
    ]
